name: Package Application with Pyinstaller

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: src

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: icepos-exe
        path: src/dist/icepos.exe
    
    - uses: actions/download-artifact@v4
      with:
        name: icepos-exe
        path: src/dist/

    - name: Display structure of downloaded files
      run: ls -R your/destination/dir